// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://glfvydxxshkpdrrpvzxh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdsZnZ5ZHh4c2hrcGRycnB2enhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk0NDQzNDksImV4cCI6MjA1NTAyMDM0OX0.CIHWaJK6wppPztkXcw16YxCzvcPIS4RL7wJMAkn0BlM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);